-- mod-sod-mage: server-side spell_dbc rows for Regeneration /
-- Temporal Beacon. GENERATED by tools/build_sod_mage_patch.py -
-- do not edit by hand. The 4xxxxx IDs are mirrored by the client MPQ.

DELETE FROM `spell_dbc` WHERE `ID` IN (401417,400735,900001,900002);

INSERT INTO `spell_dbc` (`ID`, `Attributes`, `AttributesEx`, `CastingTimeIndex`, `InterruptFlags`, `ChannelInterruptFlags`, `DurationIndex`, `PowerType`, `ManaCost`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `Effect_2`, `Effect_3`, `EffectBasePoints_1`, `ImplicitTargetA_1`, `ImplicitTargetA_2`, `ImplicitTargetA_3`, `EffectRadiusIndex_1`, `EffectAura_1`, `EffectAura_2`, `EffectAura_3`, `EffectAuraPeriod_1`, `SpellVisualID_1`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_Mask`, `ManaCostPct`, `SchoolMask`) VALUES (401417, 0, 4, 1, 15, 31756, 27, 0, 0, 5, -1, 6, 0, 0, 54, 21, 0, 0, 0, 8, 0, 0, 1000, 12655, 2047, 'Regeneration', 16712190, 28, 64);
INSERT INTO `spell_dbc` (`ID`, `DispelType`, `Attributes`, `AttributesEx`, `CastingTimeIndex`, `DurationIndex`, `PowerType`, `ManaCost`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `Effect_2`, `Effect_3`, `EffectBasePoints_1`, `ImplicitTargetA_1`, `ImplicitTargetA_2`, `ImplicitTargetA_3`, `EffectRadiusIndex_1`, `EffectAura_1`, `EffectAura_2`, `EffectAura_3`, `EffectAuraPeriod_1`, `SpellVisualID_1`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_Mask`, `ManaCostPct`, `SchoolMask`) VALUES (400735, 1, 0, 0, 1, 9, 0, 0, 6, -1, 6, 0, 0, 7, 21, 0, 0, 0, 8, 0, 0, 1000, 37, 58, 'Temporal Beacon', 16712190, 0, 64);
INSERT INTO `spell_dbc` (`ID`, `Attributes`, `AttributesEx`, `CastingTimeIndex`, `DurationIndex`, `PowerType`, `ManaCost`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `Effect_2`, `Effect_3`, `EffectBasePoints_1`, `ImplicitTargetA_1`, `ImplicitTargetA_2`, `ImplicitTargetA_3`, `EffectRadiusIndex_1`, `EffectAura_1`, `EffectAura_2`, `EffectAura_3`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_Mask`, `ManaCostPct`, `SchoolMask`) VALUES (900001, 0, 0, 1, 0, 0, 0, 6, -1, 10, 0, 0, 0, 21, 0, 0, 0, 0, 0, 0, 58, 'Chronomantic Healing', 16712190, 0, 64);
INSERT INTO `spell_dbc` (`ID`, `Attributes`, `CastingTimeIndex`, `ProcTypeMask`, `ProcChance`, `DurationIndex`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectBasePoints_1`, `ImplicitTargetA_1`, `EffectAura_1`, `Name_Lang_enUS`, `Name_Lang_Mask`, `SchoolMask`) VALUES (900002, 192, 1, 69632, 100, 21, 1, -1, 6, 0, 1, 4, 'Temporal Beacon', 16712190, 64);

DELETE FROM `spell_script_names` WHERE `spell_id` IN (401417,400735,900002);
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(401417,'spell_sod_mage_regeneration'),
(400735,'spell_sod_mage_temporal_beacon'),
(900002,'spell_sod_mage_temporal_conversion');

DELETE FROM `spell_proc` WHERE `SpellId` IN (900002);
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES (900002, 64, 0, 0, 0, 0, 69632, 1, 2, 0, 2, 0, 0, 0, 0, 0);
